export default {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  SETTINGS: '/settings',
  SUPPLIER_REGISTRATION: '/supplier-registration',
  LEADS: '/leads',
  LEAD_DETAIL: '/leads/:id',
  CONTACT_US: '/contact-us',
  AUDIT_LOGS: '/audit-logs',
  EMAIL_SETTINGS: '/email-settings',
  CONTRACTS: '/contracts',
  USERS: '/users',
  ROLES_PERMISSION: '/roles-permission',
  ITEMS: '/items',
};
