// User Error Codes (1001-1007)
export const USER_ERROR_CODE = {
  USER_NOT_FOUND: 1001,
  USER_NOT_ACTIVE: 1003,
  USER_INVALID_PASSWORD: 1004,
  USER_INVALID_NAME: 1005,
  USER_INVALID_LANGUAGE: 1006,
  USER_INVALID_AVATAR: 1007,
  USER_ALREADY_EXISTS_ACTIVE: 1008,
  USER_ALREADY_EXISTS_INACTIVE: 1009,
  USER_USED_RECENT_PASSWORD: 1010,
} as const;

// Supplier Error Codes (1101-1102)
export const SUPPLIER_ERROR_CODE = {
  SUPPLIER_NOT_FOUND: 1101,
  SUPPLIER_TERMINATED: 1102,
} as const;

// Auth Error Codes (1201-1205)
export const AUTH_ERROR_CODE = {
  INVALID_REFRESH_TOKEN: 1201,
  RESET_REQUEST_TOO_FREQUENT: 1202,
  PASSWORD_RESET_NOT_FOUND: 1203,
  PASSWORD_RESET_ALREADY_USED: 1204,
  PASSWORD_RESET_EXPIRED: 1205,
} as const;

// Document Error Codes (1301-1303)
export const DOCUMENT_ERROR_CODE = {
  DOCUMENT_NOT_FOUND: 1301,
  DOCUMENT_INVALID: 1302,
  DOCUMENT_EXPIRED: 1303,
} as const;

// Error Code Message Mapping
export const ERROR_CODE_MESSAGE_MAPPING = {
  [USER_ERROR_CODE.USER_NOT_FOUND]: 'MSG_002',
  [USER_ERROR_CODE.USER_INVALID_PASSWORD]: 'MSG_002',
  [USER_ERROR_CODE.USER_ALREADY_EXISTS_ACTIVE]: 'MSG_010',
  [USER_ERROR_CODE.USER_ALREADY_EXISTS_INACTIVE]: 'MSG_011',
  [USER_ERROR_CODE.USER_USED_RECENT_PASSWORD]: 'MSG_015',
  [AUTH_ERROR_CODE.PASSWORD_RESET_EXPIRED]: 'MSG_014',
  [AUTH_ERROR_CODE.RESET_REQUEST_TOO_FREQUENT]: 'MSG_013',
} as const;
