export const FACTORY_DATA_CONST = {
  licenseStatusOptions: [
    {
      value: 'licensed',
      label:
        'Have a license (Please specify the factory registration number and the factory license expiration date)',
    },
    { value: 'not_licensed', label: 'Not yet licensed' },
  ],
  standardOptions: [
    {
      value: 'prod_license_large',
      label: 'Production License No. 2 (for large factories)',
    },
    {
      value: 'packing_house_cert',
      label:
        'Products pass through a packing house certified by the Provincial Public Health Office (PPHO)',
    },
    {
      value: 'prod_license_small',
      label: 'Production License SorBor 1 (for small production locations)',
    },
    { value: 'manufacturing_license', label: 'Manufacturing License' },
    {
      value: 'packing_cert',
      label:
        'Packing Plant Registration Certificate (DLD, Department of Livestock Development)',
    },
    { value: 'gmp_ghp_cert', label: 'GMP or GHP certification standards' },
    {
      value: 'slaughterhouse_license',
      label: 'Slaughterhouse License (Slaughterhouse License 2)',
    },
    {
      value: 'trimming_site_license',
      label: 'Manufacturing and trimming site license',
    },
    {
      value: 'animal_trading_license',
      label: 'Animal carcass trading license application (R 10)',
    },
    { value: 'no_license', label: 'No license/standard' },
    { value: 'meat_sale_cert', label: 'Meat Sale Certificate (Rn)' },
    { value: 'animal_feed_reg', label: 'Animal feed registration certificate' },
    {
      value: 'vet_drug_cert',
      label: 'Veterinary drug registration certificate',
    },
    {
      value: 'animal_movement_form',
      label: 'Animal carcass movement form (R3/R.4/R.5)',
    },
    { value: 'fishing_license', label: 'Fishing Business License (Section 6)' },
  ],
};

export const ADDRESS_CONST = {
  addressTypeOptions: [
    { value: 'BUSINESS', label: 'Business Address' },
    { value: 'POSTAL', label: 'Postal Address' },
    { value: 'SHIPPING', label: 'Shipping Address' },
    { value: 'BILLING', label: 'Billing Address' },
  ],
  addressStatusOptions: [
    { value: 'ACTIVE', label: 'Active' },
    { value: 'INACTIVE', label: 'Inactive' },
  ],
  addressPurposeOptions: [
    { value: 'ORDERING', label: 'Ordering' },
    { value: 'REMIT', label: 'Remit' },
    { value: 'RFQ', label: 'RFQ' },
    { value: 'SHIPPING', label: 'Shipping' },
    { value: 'BILLING', label: 'Billing' },
  ],
  countryOptions: [
    { value: 'TH', label: 'Thailand' },
    { value: 'SG', label: 'Singapore' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'ID', label: 'Indonesia' },
    { value: 'PH', label: 'Philippines' },
    { value: 'MM', label: 'Myanmar' },
    { value: 'KH', label: 'Cambodia' },
    { value: 'LA', label: 'Laos' },
    { value: 'BN', label: 'Brunei' },
  ],
};

export const THAI_PROVINCES = [
  { id: 'bangkok', label: 'Bangkok' },
  { id: 'amnat-charoen', label: 'Amnat Charoen' },
  { id: 'ang-thong', label: 'Ang Thong' },
  { id: 'bueng-kan', label: 'Bueng Kan' },
  { id: 'buriram', label: 'Buriram' },
  { id: 'chachoengsao', label: 'Chachoengsao' },
  { id: 'chai-nat', label: 'Chai Nat' },
  { id: 'chaiyaphum', label: 'Chaiyaphum' },
  { id: 'chanthaburi', label: 'Chanthaburi' },
  { id: 'chiang-mai', label: 'Chiang Mai' },
  { id: 'chiang-rai', label: 'Chiang Rai' },
  { id: 'chonburi', label: 'Chonburi' },
  { id: 'chumphon', label: 'Chumphon' },
  { id: 'kalasin', label: 'Kalasin' },
  { id: 'kamphaeng-phet', label: 'Kamphaeng Phet' },
  { id: 'kanchanaburi', label: 'Kanchanaburi' },
  { id: 'khon-kaen', label: 'Khon Kaen' },
  { id: 'krabi', label: 'Krabi' },
  { id: 'lampang', label: 'Lampang' },
  { id: 'lamphun', label: 'Lamphun' },
  { id: 'loei', label: 'Loei' },
  { id: 'lopburi', label: 'Lopburi' },
  { id: 'mae-hong-son', label: 'Mae Hong Son' },
  { id: 'maha-sarakham', label: 'Maha Sarakham' },
  { id: 'mukdahan', label: 'Mukdahan' },
  { id: 'nakhon-nayok', label: 'Nakhon Nayok' },
  { id: 'nakhon-pathom', label: 'Nakhon Pathom' },
  { id: 'nakhon-phanom', label: 'Nakhon Phanom' },
  { id: 'nakhon-ratchasima', label: 'Nakhon Ratchasima' },
  { id: 'nakhon-sawan', label: 'Nakhon Sawan' },
  { id: 'nakhon-si-thammarat', label: 'Nakhon Si Thammarat' },
  { id: 'nan', label: 'Nan' },
  { id: 'narathiwat', label: 'Narathiwat' },
  { id: 'nong-bua-lamphu', label: 'Nong Bua Lamphu' },
  { id: 'nong-khai', label: 'Nong Khai' },
  { id: 'nonthaburi', label: 'Nonthaburi' },
  { id: 'pathum-thani', label: 'Pathum Thani' },
  { id: 'pattani', label: 'Pattani' },
  { id: 'phangnga', label: 'Phangnga' },
  { id: 'phatthalung', label: 'Phatthalung' },
  { id: 'phayao', label: 'Phayao' },
  { id: 'phetchabun', label: 'Phetchabun' },
  { id: 'phetchaburi', label: 'Phetchaburi' },
  { id: 'phichit', label: 'Phichit' },
  { id: 'phitsanulok', label: 'Phitsanulok' },
  { id: 'phrae', label: 'Phrae' },
  { id: 'phuket', label: 'Phuket' },
  { id: 'prachinburi', label: 'Prachinburi' },
  { id: 'prachuap-khiri-khan', label: 'Prachuap Khiri Khan' },
  { id: 'ranong', label: 'Ranong' },
  { id: 'ratchaburi', label: 'Ratchaburi' },
  { id: 'rayong', label: 'Rayong' },
  { id: 'roi-et', label: 'Roi Et' },
  { id: 'sa-kaeo', label: 'Sa Kaeo' },
  { id: 'sakon-nakhon', label: 'Sakon Nakhon' },
  { id: 'samut-prakan', label: 'Samut Prakan' },
  { id: 'samut-sakhon', label: 'Samut Sakhon' },
  { id: 'samut-songkhram', label: 'Samut Songkhram' },
  { id: 'sara-buri', label: 'Sara Buri' },
  { id: 'satun', label: 'Satun' },
  { id: 'sing-buri', label: 'Sing Buri' },
  { id: 'sisaket', label: 'Sisaket' },
  { id: 'songkhla', label: 'Songkhla' },
  { id: 'sukhothai', label: 'Sukhothai' },
  { id: 'suphanburi', label: 'Suphanburi' },
  { id: 'surat-thani', label: 'Surat Thani' },
  { id: 'surin', label: 'Surin' },
  { id: 'tak', label: 'Tak' },
  { id: 'trang', label: 'Trang' },
  { id: 'trat', label: 'Trat' },
  { id: 'ubon-ratchathani', label: 'Ubon Ratchathani' },
  { id: 'udon-thani', label: 'Udon Thani' },
  { id: 'uthai-thani', label: 'Uthai Thani' },
  { id: 'uttaradit', label: 'Uttaradit' },
  { id: 'yala', label: 'Yala' },
  { id: 'yasothon', label: 'Yasothon' },
];

export enum EBusinessUnit {
  LOTUS = 'LOTUS',
  MAKRO = 'MAKRO',
}
